import os
import sys

if sys.stdout.encoding != 'utf-8':
    try:
        sys.stdout.reconfigure(encoding='utf-8', errors='replace')
    except Exception:
        pass

user_data = """#separator:tab
#html:true
#tags:TOEIC_Listening_Test1

Part 1 - Câu 1<br><br><img src="part1_q01.png"><br>[sound:part1_q01.mp3]<br><br><div class="mc-container" data-ans="A"><button class="mc-btn" onclick="checkMC(this, 'A')">(A) She’s eating in a picnic area.</button><button class="mc-btn" onclick="checkMC(this, 'B')">(B) She’s waiting in line at a food truck.</button><button class="mc-btn" onclick="checkMC(this, 'C')">(C) She’s wiping off a bench.</button><button class="mc-btn" onclick="checkMC(this, 'D')">(D) She’s throwing away a plate.</button></div><script>function checkMC(btn, choice){var parent = btn.parentElement; if(parent.dataset.answered) return; parent.dataset.answered = "true"; var correct = parent.dataset.ans; var btns = parent.getElementsByTagName("button"); for(var i=0; i<btns.length; i++){ if(btns[i].textContent.trim().startsWith("(" + correct + ")")){ btns[i].style.background = "#28a745"; btns[i].style.color = "#fff"; } } if(choice !== correct){ btn.style.background = "#dc3545"; btn.style.color = "#fff"; }}</script>\t<b>Đáp án đúng: (A)</b><br><br><b>Giải thích:</b> Người phụ nữ đang ngồi ăn ở bàn dã ngoại ngoài trời.
Part 1 - Câu 2<br><br><img src="part1_q02.png"><br>[sound:part1_q02.mp3]<br><br><div class="mc-container" data-ans="B"><button class="mc-btn" onclick="checkMC(this, 'A')">(A) The man is brushing snow off the roof of a car.</button><button class="mc-btn" onclick="checkMC(this, 'B')">(B) The man is standing in the snow beside a car.</button><button class="mc-btn" onclick="checkMC(this, 'C')">(C) The man is shoveling snow from a walkway.</button><button class="mc-btn" onclick="checkMC(this, 'D')">(D) The man is running through the snow.</button></div>\t<b>Đáp án đúng: (B)</b><br><br><b>Giải thích:</b> Người đàn ông đang đứng trong tuyết ngay cạnh ô tô.
Part 1 - Câu 3<br><br><img src="part1_q03.png"><br>[sound:part1_q03.mp3]<br><br><div class="mc-container" data-ans="B"><button class="mc-btn" onclick="checkMC(this, 'A')">(A) Some workers are hanging art in a gallery.</button><button class="mc-btn" onclick="checkMC(this, 'B')">(B) Two of the people are having a conversation.</button><button class="mc-btn" onclick="checkMC(this, 'C')">(C) One of the men is rearranging cushions on a sofa.</button><button class="mc-btn" onclick="checkMC(this, 'D')">(D) One of the men is painting a picture.</button></div>\t<b>Đáp án đúng: (B)</b><br><br><b>Giải thích:</b> Hai người ở bên trái đang trò chuyện với nhau.
Part 1 - Câu 4<br><br><img src="part1_q04.png"><br>[sound:part1_q04.mp3]<br><br><div class="mc-container" data-ans="D"><button class="mc-btn" onclick="checkMC(this, 'A')">(A) Vehicles are entering a parking garage.</button><button class="mc-btn" onclick="checkMC(this, 'B')">(B) Clothes hangers are scattered on the ground.</button><button class="mc-btn" onclick="checkMC(this, 'C')">(C) Empty racks are lined up next to a building.</button><button class="mc-btn" onclick="checkMC(this, 'D')">(D) Clothing is being displayed under a tent.</button></div>\t<b>Đáp án đúng: (D)</b><br><br><b>Giải thích:</b> Quần áo trên giá treo được trưng bày bên dưới một chiếc lều.
Part 1 - Câu 5<br><br><img src="part1_q05.png"><br>[sound:part1_q05.mp3]<br><br><div class="mc-container" data-ans="C"><button class="mc-btn" onclick="checkMC(this, 'A')">(A) Potted plants have been suspended from a ceiling.</button><button class="mc-btn" onclick="checkMC(this, 'B')">(B) Chairs have been stacked in front of an entryway.</button><button class="mc-btn" onclick="checkMC(this, 'C')">(C) A computer station has been set up on a desk.</button><button class="mc-btn" onclick="checkMC(this, 'D')">(D) A rug has been rolled up against a wall.</button></div>\t<b>Đáp án đúng: (C)</b><br><br><b>Giải thích:</b> Một máy vi tính và máy in được lắp đặt sẵn trên bàn làm việc.
Part 1 - Câu 6<br><br><img src="part1_q06.png"><br>[sound:part1_q06.mp3]<br><br><div class="mc-container" data-ans="C"><button class="mc-btn" onclick="checkMC(this, 'A')">(A) One of the men is sweeping a patio.</button><button class="mc-btn" onclick="checkMC(this, 'B')">(B) One of the men is replacing some flooring.</button><button class="mc-btn" onclick="checkMC(this, 'C')">(C) A door has been taken off its frame.</button><button class="mc-btn" onclick="checkMC(this, 'D')">(D) A light fixture has been left on the ground.</button></div>\t<b>Đáp án đúng: (C)</b><br><br><b>Giải thích:</b> Cánh cửa phòng đã được tháo rời khỏi khung bản lề.
Part 2 - Câu 7<br><br>[sound:part2_q07.mp3]<br><b>How old is this building?</b><br><br><div class="mc-container" data-ans="B"><button class="mc-btn" onclick="checkMC(this, 'A')">(A) To ship some materials.</button><button class="mc-btn" onclick="checkMC(this, 'B')">(B) About 10 years old.</button><button class="mc-btn" onclick="checkMC(this, 'C')">(C) Company offices, I think.</button></div>\t<b>Đáp án đúng: (B) About 10 years old.</b><br><br><i>Ngữ cảnh:</i> Hỏi về độ tuổi của tòa nhà ("How old...?").
Part 2 - Câu 8<br><br>[sound:part2_q08.mp3]<br><b>Can you come to my jazz performance tonight?</b><br><br><div class="mc-container" data-ans="C"><button class="mc-btn" onclick="checkMC(this, 'A')">(A) I’m sorry I was late for the meeting.</button><button class="mc-btn" onclick="checkMC(this, 'B')">(B) Mostly just local musicians.</button><button class="mc-btn" onclick="checkMC(this, 'C')">(C) Sure, I’ll be there.</button></div>\t<b>Đáp án đúng: (C) Sure, I’ll be there.</b><br><br><i>Ngữ cảnh:</i> Lời mời đến xem biểu diễn nhạc jazz tối nay.
Part 2 - Câu 9<br><br>[sound:part2_q09.mp3]<br><b>Which apartment submitted a work order?</b><br><br><div class="mc-container" data-ans="C"><button class="mc-btn" onclick="checkMC(this, 'A')">(A) It’s what you did for a living.</button><button class="mc-btn" onclick="checkMC(this, 'B')">(B) Submit your assignment here.</button><button class="mc-btn" onclick="checkMC(this, 'C')">(C) It came from the tenants in B23.</button></div>\t<b>Đáp án đúng: (C) It came from the tenants in B23.</b><br><br><i>Ngữ cảnh:</i> Căn hộ nào đã gửi phiếu yêu cầu sửa chữa.
Part 2 - Câu 10<br><br>[sound:part2_q10.mp3]<br><b>Will you contact the vendor about changing our delivery date?</b><br><br><div class="mc-container" data-ans="A"><button class="mc-btn" onclick="checkMC(this, 'A')">(A) Of course, I’ll take care of it.</button><button class="mc-btn" onclick="checkMC(this, 'B')">(B) An email receipt.</button><button class="mc-btn" onclick="checkMC(this, 'C')">(C) Could I get change for a dollar?</button></div>\t<b>Đáp án đúng: (A) Of course, I’ll take care of it.</b><br><br><i>Ngữ cảnh:</i> Bạn liên hệ với bên bán để đổi ngày giao hàng nhé.
Part 2 - Câu 11<br><br>[sound:part2_q11.mp3]<br><b>Why was the maintenance worker here?</b><br><br><div class="mc-container" data-ans="C"><button class="mc-btn" onclick="checkMC(this, 'A')">(A) No, he didn’t.</button><button class="mc-btn" onclick="checkMC(this, 'B')">(B) From 3 o’clock until 4.</button><button class="mc-btn" onclick="checkMC(this, 'C')">(C) Because a light needed to be fixed.</button></div>\t<b>Đáp án đúng: (C) Because a light needed to be fixed.</b><br><br><i>Ngữ cảnh:</i> Hỏi lý do nhân viên bảo trì đến $\\rightarrow$ vì có bóng đèn cần sửa.
Part 2 - Câu 12<br><br>[sound:part2_q12.mp3]<br><b>Did management make a hiring decision yet?</b><br><br><div class="mc-container" data-ans="C"><button class="mc-btn" onclick="checkMC(this, 'A')">(A) Put it on the highest shelf.</button><button class="mc-btn" onclick="checkMC(this, 'B')">(B) The personnel department.</button><button class="mc-btn" onclick="checkMC(this, 'C')">(C) Yes, they chose Jacob Borgman.</button></div>\t<b>Đáp án đúng: (C) Yes, they chose Jacob Borgman.</b><br><br><i>Ngữ cảnh:</i> Ban quản lý đã ra quyết định tuyển dụng chưa.
Part 2 - Câu 13<br><br>[sound:part2_q13.mp3]<br><b>Do you want to eat here in our cafeteria or go out?</b><br><br><div class="mc-container" data-ans="C"><button class="mc-btn" onclick="checkMC(this, 'A')">(A) He went there yesterday.</button><button class="mc-btn" onclick="checkMC(this, 'B')">(B) Well, maybe a sandwich.</button><button class="mc-btn" onclick="checkMC(this, 'C')">(C) Let’s eat here.</button></div>\t<b>Đáp án đúng: (C) Let’s eat here.</b><br><br><i>Ngữ cảnh:</i> Câu hỏi lựa chọn ăn ở căng-tin hay ra ngoài ăn.
Part 2 - Câu 14<br><br>[sound:part2_q14.mp3]<br><b>Didn’t you email the employment contract to Mr. Patel yesterday?</b><br><br><div class="mc-container" data-ans="B"><button class="mc-btn" onclick="checkMC(this, 'A')">(A) Yes, I would agree.</button><button class="mc-btn" onclick="checkMC(this, 'B')">(B) No, I’ll send it now.</button><button class="mc-btn" onclick="checkMC(this, 'C')">(C) Check the employee manual.</button></div>\t<b>Đáp án đúng: (B) No, I’ll send it now.</b><br><br><i>Ngữ cảnh:</i> Bạn chưa gửi hợp đồng lao động qua email cho ông Patel hôm qua à?
Part 2 - Câu 15<br><br>[sound:part2_q15.mp3]<br><b>Our division’s picnic is this Saturday, right?</b><br><br><div class="mc-container" data-ans="A"><button class="mc-btn" onclick="checkMC(this, 'A')">(A) There’s a lot of rain in the forecast.</button><button class="mc-btn" onclick="checkMC(this, 'B')">(B) Sure, I like salad.</button><button class="mc-btn" onclick="checkMC(this, 'C')">(C) At the end of this corridor.</button></div>\t<b>Đáp án đúng: (A) There’s a lot of rain in the forecast.</b><br><br><i>Ngữ cảnh:</i> Hỏi về buổi dã ngoại thứ 7 $\\rightarrow$ câu trả lời gián tiếp: dự báo trời mưa to.
Part 2 - Câu 16<br><br>[sound:part2_q16.mp3]<br><b>Would you like coffee or tea?</b><br><br><div class="mc-container" data-ans="A"><button class="mc-btn" onclick="checkMC(this, 'A')">(A) Just water, please.</button><button class="mc-btn" onclick="checkMC(this, 'B')">(B) For a few dollars more.</button><button class="mc-btn" onclick="checkMC(this, 'C')">(C) A 15-minute break.</button></div>\t<b>Đáp án đúng: (A) Just water, please.</b><br><br><i>Ngữ cảnh:</i> Chọn đồ uống khác so với 2 lựa chọn gợi ý.
Part 2 - Câu 17<br><br>[sound:part2_q17.mp3]<br><b>We achieved our sales targets this month.</b><br><br><div class="mc-container" data-ans="A"><button class="mc-btn" onclick="checkMC(this, 'A')">(A) That’s excellent news.</button><button class="mc-btn" onclick="checkMC(this, 'B')">(B) A few times a day.</button><button class="mc-btn" onclick="checkMC(this, 'C')">(C) To the end of April.</button></div>\t<b>Đáp án đúng: (A) That’s excellent news.</b><br><br><i>Ngữ cảnh:</i> Phản hồi câu thông báo đạt chỉ tiêu doanh số.
Part 2 - Câu 18<br><br>[sound:part2_q18.mp3]<br><b>How often do you travel for your job?</b><br><br><div class="mc-container" data-ans="C"><button class="mc-btn" onclick="checkMC(this, 'A')">(A) It turned out well.</button><button class="mc-btn" onclick="checkMC(this, 'B')">(B) Yes, I did find one.</button><button class="mc-btn" onclick="checkMC(this, 'C')">(C) About once a month.</button></div>\t<b>Đáp án đúng: (C) About once a month.</b><br><br><i>Ngữ cảnh:</i> Hỏi tần suất đi công tác $\\rightarrow$ Khoảng mỗi tháng một lần.
Part 2 - Câu 19<br><br>[sound:part2_q19.mp3]<br><b>We should hike the Wildflower Trail today.</b><br><br><div class="mc-container" data-ans="B"><button class="mc-btn" onclick="checkMC(this, 'A')">(A) This seat is available.</button><button class="mc-btn" onclick="checkMC(this, 'B')">(B) I didn’t bring boots.</button><button class="mc-btn" onclick="checkMC(this, 'C')">(C) At the visitors’ center.</button></div>\t<b>Đáp án đúng: (B) I didn’t bring boots.</b><br><br><i>Ngữ cảnh:</i> Rủ đi leo núi đường mòn Wildflower Trail $\\rightarrow$ từ chối vì không mang giày bốt.
Part 2 - Câu 20<br><br>[sound:part2_q20.mp3]<br><b>You’ve booked a hotel in London, haven’t you?</b><br><br><div class="mc-container" data-ans="C"><button class="mc-btn" onclick="checkMC(this, 'A')">(A) Very enjoyable, thanks.</button><button class="mc-btn" onclick="checkMC(this, 'B')">(B) He usually takes the train.</button><button class="mc-btn" onclick="checkMC(this, 'C')">(C) Yes, I made a reservation last week.</button></div>\t<b>Đáp án đúng: (C) Yes, I made a reservation last week.</b><br><br><i>Ngữ cảnh:</i> Xác nhận đã đặt phòng khách sạn ở London chưa.
Part 2 - Câu 21<br><br>[sound:part2_q21.mp3]<br><b>Are there any tickets left for tonight’s concert?</b><br><br><div class="mc-container" data-ans="A"><button class="mc-btn" onclick="checkMC(this, 'A')">(A) It’s sold out.</button><button class="mc-btn" onclick="checkMC(this, 'B')">(B) He’s a concert violinist.</button><button class="mc-btn" onclick="checkMC(this, 'C')">(C) They already left.</button></div>\t<b>Đáp án đúng: (A) It’s sold out.</b><br><br><i>Ngữ cảnh:</i> Còn vé hòa nhạc tối nay không $\\rightarrow$ Hết vé rồi.
Part 2 - Câu 22<br><br>[sound:part2_q22.mp3]<br><b>Haven’t you used this software before?</b><br><br><div class="mc-container" data-ans="B"><button class="mc-btn" onclick="checkMC(this, 'A')">(A) Can I take your order?</button><button class="mc-btn" onclick="checkMC(this, 'B')">(B) I haven’t had the chance.</button><button class="mc-btn" onclick="checkMC(this, 'C')">(C) About $40.</button></div>\t<b>Đáp án đúng: (B) I haven’t had the chance.</b><br><br><i>Ngữ cảnh:</i> Bạn chưa từng dùng phần mềm này trước đây à $\\rightarrow$ Chưa có cơ hội dùng.
Part 2 - Câu 23<br><br>[sound:part2_q23.mp3]<br><b>When is the new blender going to be released?</b><br><br><div class="mc-container" data-ans="C"><button class="mc-btn" onclick="checkMC(this, 'A')">(A) Only with fruits and vegetables.</button><button class="mc-btn" onclick="checkMC(this, 'B')">(B) In the kitchen cabinet.</button><button class="mc-btn" onclick="checkMC(this, 'C')">(C) The prototype is still being tested.</button></div>\t<b>Đáp án đúng: (C) The prototype is still being tested.</b><br><br><i>Ngữ cảnh:</i> Khi nào máy xay ra mắt $\\rightarrow$ Bản mẫu vẫn đang được thử nghiệm.
Part 2 - Câu 24<br><br>[sound:part2_q24.mp3]<br><b>Who’s picking up our clients at the airport?</b><br><br><div class="mc-container" data-ans="A"><button class="mc-btn" onclick="checkMC(this, 'A')">(A) They decided to drive.</button><button class="mc-btn" onclick="checkMC(this, 'B')">(B) At Terminal 2.</button><button class="mc-btn" onclick="checkMC(this, 'C')">(C) It’s a marketing position.</button></div>\t<b>Đáp án đúng: (A) They decided to drive.</b><br><br><i>Ngữ cảnh:</i> Ai đón khách ở sân bay $\\rightarrow$ Khách tự lái xe đến rồi.
Part 2 - Câu 25<br><br>[sound:part2_q25.mp3]<br><b>Where are the red roses that came in this morning?</b><br><br><div class="mc-container" data-ans="C"><button class="mc-btn" onclick="checkMC(this, 'A')">(A) About 3 liters of water.</button><button class="mc-btn" onclick="checkMC(this, 'B')">(B) No, I didn’t check out the sale.</button><button class="mc-btn" onclick="checkMC(this, 'C')">(C) I needed some for a large bouquet.</button></div>\t<b>Đáp án đúng: (C) I needed some for a large bouquet.</b><br><br><i>Ngữ cảnh:</i> Hoa hồng sáng nay đâu rồi $\\rightarrow$ Tôi lấy làm bó hoa lớn rồi.
Part 2 - Câu 26<br><br>[sound:part2_q26.mp3]<br><b>This film has been nominated for several awards.</b><br><br><div class="mc-container" data-ans="A"><button class="mc-btn" onclick="checkMC(this, 'A')">(A) Why don’t we go see it?</button><button class="mc-btn" onclick="checkMC(this, 'B')">(B) After the announcement.</button><button class="mc-btn" onclick="checkMC(this, 'C')">(C) He made a great speech.</button></div>\t<b>Đáp án đúng: (A) Why don’t we go see it?</b><br><br><i>Ngữ cảnh:</i> Phim được đề cử giải $\\rightarrow$ rủ cùng đi xem.
Part 2 - Câu 27<br><br>[sound:part2_q27.mp3]<br><b>Who’s interested in starting a carpool program?</b><br><br><div class="mc-container" data-ans="B"><button class="mc-btn" onclick="checkMC(this, 'A')">(A) Thanks, but I can’t swim.</button><button class="mc-btn" onclick="checkMC(this, 'B')">(B) Clara’s already organizing one.</button><button class="mc-btn" onclick="checkMC(this, 'C')">(C) It’s a very interesting article.</button></div>\t<b>Đáp án đúng: (B) Clara’s already organizing one.</b><br><br><i>Ngữ cảnh:</i> Ai muốn tổ chức đi chung xe $\\rightarrow$ Clara đang phụ trách làm rồi.
Part 2 - Câu 28<br><br>[sound:part2_q28.mp3]<br><b>Where will I teach my workshop this month?</b><br><br><div class="mc-container" data-ans="A"><button class="mc-btn" onclick="checkMC(this, 'A')">(A) We just sent an email to all instructors.</button><button class="mc-btn" onclick="checkMC(this, 'B')">(B) 5 to 7 months.</button><button class="mc-btn" onclick="checkMC(this, 'C')">(C) Yes, it’s a beautiful building.</button></div>\t<b>Đáp án đúng: (A) We just sent an email to all instructors.</b><br><br><i>Ngữ cảnh:</i> Hỏi địa điểm dạy $\\rightarrow$ vừa gửi email cho các giảng viên.
Part 2 - Câu 29<br><br>[sound:part2_q29.mp3]<br><b>Why are we moving these sweaters to the back of the store?</b><br><br><div class="mc-container" data-ans="C"><button class="mc-btn" onclick="checkMC(this, 'A')">(A) In the new shopping mall.</button><button class="mc-btn" onclick="checkMC(this, 'B')">(B) Yes, they come in other colors.</button><button class="mc-btn" onclick="checkMC(this, 'C')">(C) Our spring merchandise is arriving soon.</button></div>\t<b>Đáp án đúng: (C) Our spring merchandise is arriving soon.</b><br><br><i>Ngữ cảnh:</i> Chuyển áo len về phía sau vì hàng mùa xuân sắp về.
Part 2 - Câu 30<br><br>[sound:part2_q30.mp3]<br><b>Would you be interested in working on some of these contracts?</b><br><br><div class="mc-container" data-ans="C"><button class="mc-btn" onclick="checkMC(this, 'A')">(A) Thank you for meeting me.</button><button class="mc-btn" onclick="checkMC(this, 'B')">(B) A contact lens prescription.</button><button class="mc-btn" onclick="checkMC(this, 'C')">(C) I have very limited time.</button></div>\t<b>Đáp án đúng: (C) I have very limited time.</b><br><br><i>Ngữ cảnh:</i> Mời làm thêm hợp đồng $\\rightarrow$ từ chối vì quỹ thời gian hạn hẹp.
Part 2 - Câu 31<br><br>[sound:part2_q31.mp3]<br><b>What type of job are you looking for?</b><br><br><div class="mc-container" data-ans="B"><button class="mc-btn" onclick="checkMC(this, 'A')">(A) No, at 10 a.m.</button><button class="mc-btn" onclick="checkMC(this, 'B')">(B) I really like working with computers.</button><button class="mc-btn" onclick="checkMC(this, 'C')">(C) Just a resume is needed.</button></div>\t<b>Đáp án đúng: (B) I really like working with computers.</b><br><br><i>Ngữ cảnh:</i> Hỏi tìm việc gì $\\rightarrow$ Tôi thích làm việc liên quan đến máy tính.
Part 3 - Câu 32<br><br>[sound:part3_c32_34.mp3]<br><b>Question 32: What event does the woman mention?</b><br><br><div class="mc-container" data-ans="A"><button class="mc-btn" onclick="checkMC(this, 'A')">(A) A company picnic</button><button class="mc-btn" onclick="checkMC(this, 'B')">(B) A retirement dinner</button><button class="mc-btn" onclick="checkMC(this, 'C')">(C) An awards ceremony</button><button class="mc-btn" onclick="checkMC(this, 'D')">(D) A training workshop</button></div>\t<b>Đáp án đúng: (A) A company picnic</b><br><br><i>Transcript:</i> "Thank you so much for organizing the annual company picnic, Jingdao."
Part 3 - Câu 33<br><br>[sound:part3_c32_34.mp3]<br><b>Question 33: What does the woman ask for?</b><br><br><div class="mc-container" data-ans="C"><button class="mc-btn" onclick="checkMC(this, 'A')">(A) Some contact information</button><button class="mc-btn" onclick="checkMC(this, 'B')">(B) A ride to an event</button><button class="mc-btn" onclick="checkMC(this, 'C')">(C) A cooking recipe</button><button class="mc-btn" onclick="checkMC-this, 'D'">(D) Extra paper plates</button></div>\t<b>Đáp án đúng: (C) A cooking recipe</b><br><br><i>Transcript:</i> "...Would you mind sharing the recipe? It was delicious."
Part 3 - Câu 34<br><br>[sound:part3_c32_34.mp3]<br><b>Question 34: What does the man recommend doing?</b><br><br><div class="mc-container" data-ans="B"><button class="mc-btn" onclick="checkMC(this, 'A')">(A) Buying ingredients at a local market</button><button class="mc-btn" onclick="checkMC(this, 'B')">(B) Watching an instructional video</button><button class="mc-btn" onclick="checkMC(this, 'C')">(C) Printing out instructions</button><button class="mc-btn" onclick="checkMC(this, 'D')">(D) Asking a colleague for assistance</button></div>\t<b>Đáp án đúng: (B) Watching an instructional video</b><br><br><i>Transcript:</i> "There's a really helpful video that walks you through all the steps. I recommend you watch it first."
"""

filename = "TOEIC_Listening_Test1_Audio_Interactive.txt"
with open(filename, "w", encoding="utf-8") as f:
    f.write(user_data.strip() + "\n")

print(f"Đã lưu {filename} ({len(user_data)} bytes)")
